### ISSUE TITLE
ToDO

### ISSUE THREAD

**Issue by alex2wong** [alex2wong/Jqmap2#3]
- [ ]  wrap this multi-client game with React PWA.

- [ ]  upgrade ws to wss to cohere with front-end https.

- [x]  fix robot generate error.
